package pe.edu.sistemas.sismanweb.entidades;
// Generated 03/05/2017 02:54:05 AM by Hibernate Tools 5.2.0.CR1

/**
 * Alumno generated by hbm2java
 */
public class Alumno implements java.io.Serializable {

	private Integer idAlumno;
	private Persona persona;
	private Plan plan;
	private TipoAlumno tipoAlumno;
	private int alumnoActivo;

	public Alumno() {
	}

	public Alumno(Persona persona, Plan plan, TipoAlumno tipoAlumno, int alumnoActivo) {
		this.persona = persona;
		this.plan = plan;
		this.tipoAlumno = tipoAlumno;
		this.alumnoActivo = alumnoActivo;
	}

	public Integer getIdAlumno() {
		return this.idAlumno;
	}

	public void setIdAlumno(Integer idAlumno) {
		this.idAlumno = idAlumno;
	}

	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public Plan getPlan() {
		return this.plan;
	}

	public void setPlan(Plan plan) {
		this.plan = plan;
	}

	public TipoAlumno getTipoAlumno() {
		return this.tipoAlumno;
	}

	public void setTipoAlumno(TipoAlumno tipoAlumno) {
		this.tipoAlumno = tipoAlumno;
	}

	public int getAlumnoActivo() {
		return this.alumnoActivo;
	}

	public void setAlumnoActivo(int alumnoActivo) {
		this.alumnoActivo = alumnoActivo;
	}

}
