package pe.edu.sistemas.sismanweb.entidades;
// Generated 10/08/2017 03:08:17 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * CategoriaDocente generated by hbm2java
 */
public class CategoriaDocente implements java.io.Serializable {

	private Short idecategoriaDocente;
	private String categoriaDocenteNombre;
	private Set docentes = new HashSet(0);

	public CategoriaDocente() {
	}

	public CategoriaDocente(String categoriaDocenteNombre) {
		this.categoriaDocenteNombre = categoriaDocenteNombre;
	}

	public CategoriaDocente(String categoriaDocenteNombre, Set docentes) {
		this.categoriaDocenteNombre = categoriaDocenteNombre;
		this.docentes = docentes;
	}

	public Short getIdecategoriaDocente() {
		return this.idecategoriaDocente;
	}

	public void setIdecategoriaDocente(Short idecategoriaDocente) {
		this.idecategoriaDocente = idecategoriaDocente;
	}

	public String getCategoriaDocenteNombre() {
		return this.categoriaDocenteNombre;
	}

	public void setCategoriaDocenteNombre(String categoriaDocenteNombre) {
		this.categoriaDocenteNombre = categoriaDocenteNombre;
	}

	public Set getDocentes() {
		return this.docentes;
	}

	public void setDocentes(Set docentes) {
		this.docentes = docentes;
	}

}
