package pe.edu.sistemas.sismanweb.entidades;
// Generated 10/08/2017 03:08:17 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * CursoConjunto generated by hbm2java
 */
public class CursoConjunto implements java.io.Serializable {

	private Integer idcursoConjunto;
	private CursoBase cursoBase;
	private String cursocNombre;
	private int cursocCodcomun;
	private Set cursoPeriodos = new HashSet(0);

	public CursoConjunto() {
	}

	public CursoConjunto(CursoBase cursoBase, String cursocNombre, int cursocCodcomun) {
		this.cursoBase = cursoBase;
		this.cursocNombre = cursocNombre;
		this.cursocCodcomun = cursocCodcomun;
	}

	public CursoConjunto(CursoBase cursoBase, String cursocNombre, int cursocCodcomun, Set cursoPeriodos) {
		this.cursoBase = cursoBase;
		this.cursocNombre = cursocNombre;
		this.cursocCodcomun = cursocCodcomun;
		this.cursoPeriodos = cursoPeriodos;
	}

	public Integer getIdcursoConjunto() {
		return this.idcursoConjunto;
	}

	public void setIdcursoConjunto(Integer idcursoConjunto) {
		this.idcursoConjunto = idcursoConjunto;
	}

	public CursoBase getCursoBase() {
		return this.cursoBase;
	}

	public void setCursoBase(CursoBase cursoBase) {
		this.cursoBase = cursoBase;
	}

	public String getCursocNombre() {
		return this.cursocNombre;
	}

	public void setCursocNombre(String cursocNombre) {
		this.cursocNombre = cursocNombre;
	}

	public int getCursocCodcomun() {
		return this.cursocCodcomun;
	}

	public void setCursocCodcomun(int cursocCodcomun) {
		this.cursocCodcomun = cursocCodcomun;
	}

	public Set getCursoPeriodos() {
		return this.cursoPeriodos;
	}

	public void setCursoPeriodos(Set cursoPeriodos) {
		this.cursoPeriodos = cursoPeriodos;
	}

}
