package pe.edu.sistemas.sismanweb.entidades;
// Generated 10/08/2017 03:08:17 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * DepartamentoAcademico generated by hbm2java
 */
public class DepartamentoAcademico implements java.io.Serializable {

	private int iddepartamentoAcademico;
	private String departamentoAcademicoNombre;
	private Set docentes = new HashSet(0);

	public DepartamentoAcademico() {
	}

	public DepartamentoAcademico(int iddepartamentoAcademico, String departamentoAcademicoNombre) {
		this.iddepartamentoAcademico = iddepartamentoAcademico;
		this.departamentoAcademicoNombre = departamentoAcademicoNombre;
	}

	public DepartamentoAcademico(int iddepartamentoAcademico, String departamentoAcademicoNombre, Set docentes) {
		this.iddepartamentoAcademico = iddepartamentoAcademico;
		this.departamentoAcademicoNombre = departamentoAcademicoNombre;
		this.docentes = docentes;
	}

	public int getIddepartamentoAcademico() {
		return this.iddepartamentoAcademico;
	}

	public void setIddepartamentoAcademico(int iddepartamentoAcademico) {
		this.iddepartamentoAcademico = iddepartamentoAcademico;
	}

	public String getDepartamentoAcademicoNombre() {
		return this.departamentoAcademicoNombre;
	}

	public void setDepartamentoAcademicoNombre(String departamentoAcademicoNombre) {
		this.departamentoAcademicoNombre = departamentoAcademicoNombre;
	}

	public Set getDocentes() {
		return this.docentes;
	}

	public void setDocentes(Set docentes) {
		this.docentes = docentes;
	}

}
