package pe.edu.sistemas.sismanweb.entidades;
// Generated 03/05/2017 02:54:05 AM by Hibernate Tools 5.2.0.CR1

import java.util.Date;

/**
 * Persona generated by hbm2java
 */
public class Persona implements java.io.Serializable {

	private Integer idPersona;
	private String personaCodigo;
	private String personaNombre;
	private String personaAppaterno;
	private String personaApmaterno;
	private String personaTelefono;
	private String personaCorreo;
	private String personaDireccion;
	private String personaDni;
	private Date personaFechaNacimiento;
	private String personaSexo;
	private String personaEstadoCivil;
	private String personaCodigoSistema;
	private String personaPasswordSistema;
	private String personaPasswordSistema2;

	public Persona() {
	}

	public Persona(String personaCodigoSistema, String personaPasswordSistema, String personaPasswordSistema2) {
		this.personaCodigoSistema = personaCodigoSistema;
		this.personaPasswordSistema = personaPasswordSistema;
		this.personaPasswordSistema2 = personaPasswordSistema2;
	}

	public Persona(String personaCodigo, String personaNombre, String personaAppaterno, String personaApmaterno,
			String personaTelefono, String personaCorreo, String personaDireccion, String personaDni,
			Date personaFechaNacimiento, String personaSexo, String personaEstadoCivil, String personaCodigoSistema,
			String personaPasswordSistema, String personaPasswordSistema2) {
		this.personaCodigo = personaCodigo;
		this.personaNombre = personaNombre;
		this.personaAppaterno = personaAppaterno;
		this.personaApmaterno = personaApmaterno;
		this.personaTelefono = personaTelefono;
		this.personaCorreo = personaCorreo;
		this.personaDireccion = personaDireccion;
		this.personaDni = personaDni;
		this.personaFechaNacimiento = personaFechaNacimiento;
		this.personaSexo = personaSexo;
		this.personaEstadoCivil = personaEstadoCivil;
		this.personaCodigoSistema = personaCodigoSistema;
		this.personaPasswordSistema = personaPasswordSistema;
		this.personaPasswordSistema2 = personaPasswordSistema2;
	}

	public Integer getIdPersona() {
		return this.idPersona;
	}

	public void setIdPersona(Integer idPersona) {
		this.idPersona = idPersona;
	}

	public String getPersonaCodigo() {
		return this.personaCodigo;
	}

	public void setPersonaCodigo(String personaCodigo) {
		this.personaCodigo = personaCodigo;
	}

	public String getPersonaNombre() {
		return this.personaNombre;
	}

	public void setPersonaNombre(String personaNombre) {
		this.personaNombre = personaNombre;
	}

	public String getPersonaAppaterno() {
		return this.personaAppaterno;
	}

	public void setPersonaAppaterno(String personaAppaterno) {
		this.personaAppaterno = personaAppaterno;
	}

	public String getPersonaApmaterno() {
		return this.personaApmaterno;
	}

	public void setPersonaApmaterno(String personaApmaterno) {
		this.personaApmaterno = personaApmaterno;
	}

	public String getPersonaTelefono() {
		return this.personaTelefono;
	}

	public void setPersonaTelefono(String personaTelefono) {
		this.personaTelefono = personaTelefono;
	}

	public String getPersonaCorreo() {
		return this.personaCorreo;
	}

	public void setPersonaCorreo(String personaCorreo) {
		this.personaCorreo = personaCorreo;
	}

	public String getPersonaDireccion() {
		return this.personaDireccion;
	}

	public void setPersonaDireccion(String personaDireccion) {
		this.personaDireccion = personaDireccion;
	}

	public String getPersonaDni() {
		return this.personaDni;
	}

	public void setPersonaDni(String personaDni) {
		this.personaDni = personaDni;
	}

	public Date getPersonaFechaNacimiento() {
		return this.personaFechaNacimiento;
	}

	public void setPersonaFechaNacimiento(Date personaFechaNacimiento) {
		this.personaFechaNacimiento = personaFechaNacimiento;
	}

	public String getPersonaSexo() {
		return this.personaSexo;
	}

	public void setPersonaSexo(String personaSexo) {
		this.personaSexo = personaSexo;
	}

	public String getPersonaEstadoCivil() {
		return this.personaEstadoCivil;
	}

	public void setPersonaEstadoCivil(String personaEstadoCivil) {
		this.personaEstadoCivil = personaEstadoCivil;
	}

	public String getPersonaCodigoSistema() {
		return this.personaCodigoSistema;
	}

	public void setPersonaCodigoSistema(String personaCodigoSistema) {
		this.personaCodigoSistema = personaCodigoSistema;
	}

	public String getPersonaPasswordSistema() {
		return this.personaPasswordSistema;
	}

	public void setPersonaPasswordSistema(String personaPasswordSistema) {
		this.personaPasswordSistema = personaPasswordSistema;
	}

	public String getPersonaPasswordSistema2() {
		return this.personaPasswordSistema2;
	}

	public void setPersonaPasswordSistema2(String personaPasswordSistema2) {
		this.personaPasswordSistema2 = personaPasswordSistema2;
	}

}
