package pe.edu.sistemas.sismanweb.entidades;
// Generated 10/08/2017 03:08:17 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Plan generated by hbm2java
 */
public class Plan implements java.io.Serializable {

	private Integer idplan;
	private int escuelaIdescuela;
	private String planNombre;
	private Set alumnos = new HashSet(0);
	private Set cursoBases = new HashSet(0);

	public Plan() {
	}

	public Plan(int escuelaIdescuela, String planNombre) {
		this.escuelaIdescuela = escuelaIdescuela;
		this.planNombre = planNombre;
	}

	public Plan(int escuelaIdescuela, String planNombre, Set alumnos, Set cursoBases) {
		this.escuelaIdescuela = escuelaIdescuela;
		this.planNombre = planNombre;
		this.alumnos = alumnos;
		this.cursoBases = cursoBases;
	}

	public Integer getIdplan() {
		return this.idplan;
	}

	public void setIdplan(Integer idplan) {
		this.idplan = idplan;
	}

	public int getEscuelaIdescuela() {
		return this.escuelaIdescuela;
	}

	public void setEscuelaIdescuela(int escuelaIdescuela) {
		this.escuelaIdescuela = escuelaIdescuela;
	}

	public String getPlanNombre() {
		return this.planNombre;
	}

	public void setPlanNombre(String planNombre) {
		this.planNombre = planNombre;
	}

	public Set getAlumnos() {
		return this.alumnos;
	}

	public void setAlumnos(Set alumnos) {
		this.alumnos = alumnos;
	}

	public Set getCursoBases() {
		return this.cursoBases;
	}

	public void setCursoBases(Set cursoBases) {
		this.cursoBases = cursoBases;
	}

}
