package pe.edu.sistemas.sismanweb.entidades;
// Generated 10/08/2017 03:08:17 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TipoAlumno generated by hbm2java
 */
public class TipoAlumno implements java.io.Serializable {

	private Integer idTipoAlumno;
	private String tipoAlumnoNombre;
	private Set alumnos = new HashSet(0);

	public TipoAlumno() {
	}

	public TipoAlumno(String tipoAlumnoNombre) {
		this.tipoAlumnoNombre = tipoAlumnoNombre;
	}

	public TipoAlumno(String tipoAlumnoNombre, Set alumnos) {
		this.tipoAlumnoNombre = tipoAlumnoNombre;
		this.alumnos = alumnos;
	}

	public Integer getIdTipoAlumno() {
		return this.idTipoAlumno;
	}

	public void setIdTipoAlumno(Integer idTipoAlumno) {
		this.idTipoAlumno = idTipoAlumno;
	}

	public String getTipoAlumnoNombre() {
		return this.tipoAlumnoNombre;
	}

	public void setTipoAlumnoNombre(String tipoAlumnoNombre) {
		this.tipoAlumnoNombre = tipoAlumnoNombre;
	}

	public Set getAlumnos() {
		return this.alumnos;
	}

	public void setAlumnos(Set alumnos) {
		this.alumnos = alumnos;
	}

}
