package pe.edu.sistemas.sismanweb.entidades;
// Generated 10/08/2017 03:08:17 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TipoUsuario generated by hbm2java
 */
public class TipoUsuario implements java.io.Serializable {

	private Integer idtipoUsuario;
	private String nombreTipoUsuario;
	private String tipoUsuarioDescripcion;
	private Set usuarios = new HashSet(0);

	public TipoUsuario() {
	}

	public TipoUsuario(String nombreTipoUsuario) {
		this.nombreTipoUsuario = nombreTipoUsuario;
	}

	public TipoUsuario(String nombreTipoUsuario, String tipoUsuarioDescripcion, Set usuarios) {
		this.nombreTipoUsuario = nombreTipoUsuario;
		this.tipoUsuarioDescripcion = tipoUsuarioDescripcion;
		this.usuarios = usuarios;
	}

	public Integer getIdtipoUsuario() {
		return this.idtipoUsuario;
	}

	public void setIdtipoUsuario(Integer idtipoUsuario) {
		this.idtipoUsuario = idtipoUsuario;
	}

	public String getNombreTipoUsuario() {
		return this.nombreTipoUsuario;
	}

	public void setNombreTipoUsuario(String nombreTipoUsuario) {
		this.nombreTipoUsuario = nombreTipoUsuario;
	}

	public String getTipoUsuarioDescripcion() {
		return this.tipoUsuarioDescripcion;
	}

	public void setTipoUsuarioDescripcion(String tipoUsuarioDescripcion) {
		this.tipoUsuarioDescripcion = tipoUsuarioDescripcion;
	}

	public Set getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set usuarios) {
		this.usuarios = usuarios;
	}

}
