package pe.edu.sistemas.sismanweb.entidades;
// Generated 10/08/2017 03:08:17 PM by Hibernate Tools 4.3.1.Final

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private Integer idUsuario;
	private Persona persona;
	private TipoUsuario tipoUsuario;
	private Integer usuarioActivo;
	private int sistemaIdSistema;

	public Usuario() {
	}

	public Usuario(Persona persona, TipoUsuario tipoUsuario, int sistemaIdSistema) {
		this.persona = persona;
		this.tipoUsuario = tipoUsuario;
		this.sistemaIdSistema = sistemaIdSistema;
	}

	public Usuario(Persona persona, TipoUsuario tipoUsuario, Integer usuarioActivo, int sistemaIdSistema) {
		this.persona = persona;
		this.tipoUsuario = tipoUsuario;
		this.usuarioActivo = usuarioActivo;
		this.sistemaIdSistema = sistemaIdSistema;
	}

	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	public TipoUsuario getTipoUsuario() {
		return this.tipoUsuario;
	}

	public void setTipoUsuario(TipoUsuario tipoUsuario) {
		this.tipoUsuario = tipoUsuario;
	}

	public Integer getUsuarioActivo() {
		return this.usuarioActivo;
	}

	public void setUsuarioActivo(Integer usuarioActivo) {
		this.usuarioActivo = usuarioActivo;
	}

	public int getSistemaIdSistema() {
		return this.sistemaIdSistema;
	}

	public void setSistemaIdSistema(int sistemaIdSistema) {
		this.sistemaIdSistema = sistemaIdSistema;
	}

}
