package pe.edu.sistemas.sismanweb.domain;
// Generated 18/09/2018 05:06:44 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HorarioClase generated by hbm2java
 */
@Entity
@Table(name = "horario_clase", catalog = "modelogeneralfisi")
public class HorarioClase implements java.io.Serializable {

	private Integer idhorarioClase;
	private Aula aula;
	private Docente docente;
	private Grupo grupo;
	private Date horaInicio;
	private Date horaFin;
	private String nombreAula;
	private Integer dia;
	private String horarioClaseTipo;
	private String horarioClasePeriodo;

	public HorarioClase() {
	}

	public HorarioClase(Docente docente, Grupo grupo, String horarioClaseTipo, String horarioClasePeriodo) {
		this.docente = docente;
		this.grupo = grupo;
		this.horarioClaseTipo = horarioClaseTipo;
		this.horarioClasePeriodo = horarioClasePeriodo;
	}

	public HorarioClase(Aula aula, Docente docente, Grupo grupo, Date horaInicio, Date horaFin, String nombreAula,
			Integer dia, String horarioClaseTipo, String horarioClasePeriodo) {
		this.aula = aula;
		this.docente = docente;
		this.grupo = grupo;
		this.horaInicio = horaInicio;
		this.horaFin = horaFin;
		this.nombreAula = nombreAula;
		this.dia = dia;
		this.horarioClaseTipo = horarioClaseTipo;
		this.horarioClasePeriodo = horarioClasePeriodo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IDHORARIO_CLASE", unique = true, nullable = false)
	public Integer getIdhorarioClase() {
		return this.idhorarioClase;
	}

	public void setIdhorarioClase(Integer idhorarioClase) {
		this.idhorarioClase = idhorarioClase;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AULA_IDAULA")
	public Aula getAula() {
		return this.aula;
	}

	public void setAula(Aula aula) {
		this.aula = aula;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DOCENTE_IDDOCENTE", nullable = false)
	public Docente getDocente() {
		return this.docente;
	}

	public void setDocente(Docente docente) {
		this.docente = docente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GRUPO_IDGRUPO", nullable = false)
	public Grupo getGrupo() {
		return this.grupo;
	}

	public void setGrupo(Grupo grupo) {
		this.grupo = grupo;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HORA_INICIO", length = 8)
	public Date getHoraInicio() {
		return this.horaInicio;
	}

	public void setHoraInicio(Date horaInicio) {
		this.horaInicio = horaInicio;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "HORA_FIN", length = 8)
	public Date getHoraFin() {
		return this.horaFin;
	}

	public void setHoraFin(Date horaFin) {
		this.horaFin = horaFin;
	}

	@Column(name = "AULA", length = 45)
	public String getNombreAula() {
		return this.nombreAula;
	}

	public void setNombreAula(String nombreAula) {
		this.nombreAula = nombreAula;
	}

	@Column(name = "DIA")
	public Integer getDia() {
		return this.dia;
	}

	public void setDia(Integer dia) {
		this.dia = dia;
	}

	@Column(name = "HORARIO_CLASE_TIPO", nullable = false, length = 45)
	public String getHorarioClaseTipo() {
		return this.horarioClaseTipo;
	}

	public void setHorarioClaseTipo(String horarioClaseTipo) {
		this.horarioClaseTipo = horarioClaseTipo;
	}

	@Column(name = "HORARIO_CLASE_PERIODO", nullable = false, length = 10)
	public String getHorarioClasePeriodo() {
		return this.horarioClasePeriodo;
	}

	public void setHorarioClasePeriodo(String horarioClasePeriodo) {
		this.horarioClasePeriodo = horarioClasePeriodo;
	}

}
